export const rootlyApi = {
  getClient() {
    return {
      async getServices() {
        return {
          data: [
            {
              id: "<service_id>",
              type: "services",
              attributes: {
                name: "backstage-plugin-test-service",
                slug: "backstage-plugin-test-service",
                description: "Backstage Plugin Test Service",
                public_description: "",
                notify_emails: [],
                color: "#FAEBB7",
                status: "operational",
                position: 9,
                show_uptime: true,
                show_uptime_last_days: 60,
                slack_channels: [],
                slack_aliases: [],
                github_repository_name: null,
                github_repository_branch: "master",
                gitlab_repository_name: null,
                gitlab_repository_branch: "master",
                opsgenie_id: null,
                pagerduty_id: null,
                backstage_id: "component:default/backstage-plugin-test-service",
                external_id: null,
                cortex_id: null,
                service_now_ci_sys_id: null,
                environment_ids: ["<environment_id>"],
                service_ids: [],
                owner_group_ids: ["<group_id>"],
                owners_group_ids: ["<group_id>"],
                owner_user_ids: [],
                owners_user_ids: [],
                incidents_count: 1,
                alert_urgency_id: null,
                alerts_email_enabled: false,
                alerts_email_address: "service-<service_id>@email.rootly.com",
                alert_broadcast_enabled: false,
                alert_broadcast_channel: {},
                incident_broadcast_enabled: false,
                incident_broadcast_channel: {},
                created_at: "2025-09-05T02:19:33.876-07:00",
                updated_at: "2025-09-05T02:29:40.608-07:00",
              },
            },
          ],
          links: {
            self: "https://api.rootly.com/v1/services?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            first:
              "https://api.rootly.com/v1/services?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            prev: null,
            next: null,
            last: "https://api.rootly.com/v1/services?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
          },
          meta: {
            current_page: 1,
            next_page: null,
            prev_page: null,
            total_count: 1,
            total_pages: 1,
          },
        };
      },
      async getServiceIncidentsChart() {
        return {
          data: {
            "2025-07-07 00:00:00 +0200": 0,
            "2025-07-08 00:00:00 +0200": 0,
            "2025-07-09 00:00:00 +0200": 0,
            "2025-07-10 00:00:00 +0200": 0,
            "2025-07-11 00:00:00 +0200": 0,
            "2025-07-12 00:00:00 +0200": 0,
            "2025-07-13 00:00:00 +0200": 0,
            "2025-07-14 00:00:00 +0200": 0,
            "2025-07-15 00:00:00 +0200": 0,
            "2025-07-16 00:00:00 +0200": 0,
            "2025-07-17 00:00:00 +0200": 0,
            "2025-07-18 00:00:00 +0200": 0,
            "2025-07-19 00:00:00 +0200": 0,
            "2025-07-20 00:00:00 +0200": 0,
            "2025-07-21 00:00:00 +0200": 0,
            "2025-07-22 00:00:00 +0200": 0,
            "2025-07-23 00:00:00 +0200": 0,
            "2025-07-24 00:00:00 +0200": 0,
            "2025-07-25 00:00:00 +0200": 0,
            "2025-07-26 00:00:00 +0200": 0,
            "2025-07-27 00:00:00 +0200": 0,
            "2025-07-28 00:00:00 +0200": 0,
            "2025-07-29 00:00:00 +0200": 0,
            "2025-07-30 00:00:00 +0200": 0,
            "2025-07-31 00:00:00 +0200": 0,
            "2025-08-01 00:00:00 +0200": 0,
            "2025-08-02 00:00:00 +0200": 0,
            "2025-08-03 00:00:00 +0200": 0,
            "2025-08-04 00:00:00 +0200": 0,
            "2025-08-05 00:00:00 +0200": 0,
            "2025-08-06 00:00:00 +0200": 0,
            "2025-08-07 00:00:00 +0200": 0,
            "2025-08-08 00:00:00 +0200": 0,
            "2025-08-09 00:00:00 +0200": 0,
            "2025-08-10 00:00:00 +0200": 0,
            "2025-08-11 00:00:00 +0200": 0,
            "2025-08-12 00:00:00 +0200": 0,
            "2025-08-13 00:00:00 +0200": 0,
            "2025-08-14 00:00:00 +0200": 0,
            "2025-08-15 00:00:00 +0200": 0,
            "2025-08-16 00:00:00 +0200": 0,
            "2025-08-17 00:00:00 +0200": 0,
            "2025-08-18 00:00:00 +0200": 0,
            "2025-08-19 00:00:00 +0200": 0,
            "2025-08-20 00:00:00 +0200": 0,
            "2025-08-21 00:00:00 +0200": 0,
            "2025-08-22 00:00:00 +0200": 0,
            "2025-08-23 00:00:00 +0200": 0,
            "2025-08-24 00:00:00 +0200": 0,
            "2025-08-25 00:00:00 +0200": 0,
            "2025-08-26 00:00:00 +0200": 0,
            "2025-08-27 00:00:00 +0200": 0,
            "2025-08-28 00:00:00 +0200": 0,
            "2025-08-29 00:00:00 +0200": 0,
            "2025-08-30 00:00:00 +0200": 0,
            "2025-08-31 00:00:00 +0200": 0,
            "2025-09-01 00:00:00 +0200": 0,
            "2025-09-02 00:00:00 +0200": 0,
            "2025-09-03 00:00:00 +0200": 0,
            "2025-09-04 00:00:00 +0200": 0,
            "2025-09-05 00:00:00 +0200": 1,
          },
        };
      },
      async getFunctionalities() {
        return {
          data: [
            {
              id: "<functionality_id>",
              type: "functionalities",
              attributes: {
                name: "Backstage Plugin Test Functionality",
                slug: "backstage-plugin-test-functionality",
                description: "Backstage Plugin Test Functionality",
                public_description: "",
                notify_emails: [],
                color: "#F5D9C4",
                status: "operational",
                position: 7,
                show_uptime: true,
                show_uptime_last_days: 60,
                slack_channels: [],
                slack_aliases: [],
                backstage_id: null,
                external_id: null,
                opsgenie_id: null,
                pagerduty_id: null,
                cortex_id: null,
                opslevel_id: null,
                service_now_ci_sys_id: null,
                environment_ids: ["<environment_id>"],
                service_ids: ["<service_id>"],
                owner_group_ids: ["<group_id>"],
                owners_group_ids: ["<group_id>"],
                owner_user_ids: [],
                owners_user_ids: [],
                incidents_count: 0,
                created_at: "2025-09-05T02:41:39.034-07:00",
                updated_at: "2025-09-05T02:41:39.034-07:00",
              },
            },
          ],
          links: {
            self: "https://api.rootly.com/v1/functionalities?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            first:
              "https://api.rootly.com/v1/functionalities?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            prev: null,
            next: null,
            last: "https://api.rootly.com/v1/functionalities?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
          },
          meta: {
            current_page: 1,
            next_page: null,
            prev_page: null,
            total_count: 1,
            total_pages: 1,
          },
        };
      },
      async getTeams() {
        return {
          data: [
            {
              id: "<group_id>",
              type: "groups",
              attributes: {
                slug: "backstage-plugin-test-team",
                name: "Backstage Plugin Test Team",
                description: "",
                color: "#F4CFD1",
                position: 5,
                notify_emails: [],
                slack_channels: [],
                slack_aliases: [],
                pagerduty_id: null,
                pagerduty_service_id: null,
                backstage_id: null,
                external_id: null,
                opsgenie_id: null,
                victor_ops_id: null,
                pagertree_id: null,
                cortex_id: null,
                service_now_ci_sys_id: null,
                user_ids: ["<user_id>"],
                admin_ids: [],
                incidents_count: 1,
                alert_urgency_id: null,
                alerts_email_enabled: false,
                alerts_email_address:
                  "group-<alert_email_address_id>@email.rootly.com",
                alert_broadcast_enabled: false,
                alert_broadcast_channel: {},
                incident_broadcast_enabled: false,
                incident_broadcast_channel: {},
                created_at: "2025-09-05T01:58:33.253-07:00",
                updated_at: "2025-09-05T01:58:48.834-07:00",
              },
              relationships: {
                users: {
                  data: [
                    {
                      id: "<user_id>",
                      type: "users",
                    },
                  ],
                },
              },
            },
          ],
          links: {
            self: "https://api.rootly.com/v1/teams?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            first:
              "https://api.rootly.com/v1/teams?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
            prev: null,
            next: null,
            last: "https://api.rootly.com/v1/teams?page%5Bnumber%5D=1\u0026page%5Bsize%5D=1",
          },
          meta: {
            current_page: 1,
            next_page: null,
            prev_page: null,
            total_count: 5,
            total_pages: 1,
          },
        };
      },
      async getIncidents() {
        return {
          data: [
            {
              id: "<incident_id>",
              type: "incidents",
              attributes: {
                parent_incident_id: null,
                sequential_id: 11,
                title: "Backstage Plugin Test Incident",
                slug: "backstage-plugin-test-incident",
                kind: "normal",
                private: false,
                summary: "Backstage Plugin Test Incident",
                status: "started",
                source: "web",
                url: "https://rootly.com/account/incidents/1-backstage-plugin-test-incident",
                short_url: "https://root.ly/bq3ubo",
                user: {
                  data: {
                    id: "<user_id>",
                    type: "users",
                    attributes: {
                      name: "Guest",
                      email: "guest@email.com",
                      phone: null,
                      phone_2: null,
                      first_name: "Guest",
                      last_name: "",
                      full_name: "Guest",
                      full_name_with_team: "[Rockit Rockets] Guest",
                      slack_id: "<slack_id>",
                      time_zone: "Europe/Stockholm",
                      updated_at: "2025-09-05T03:18:07.390-07:00",
                      created_at: "2025-09-04T11:26:59.737-07:00",
                    },
                    relationships: {
                      email_addresses: {
                        data: [
                          {
                            id: "<user_email_address_id>",
                            type: "user_email_addresses",
                          },
                        ],
                      },
                      phone_numbers: {
                        data: [],
                      },
                      devices: {
                        data: [],
                      },
                      role: {
                        data: {
                          created_at: "2022-07-06T07:41:27.733-07:00",
                          updated_at: "2024-10-08T23:57:01.838-07:00",
                          display_order: 3,
                          api_keys_permissions: [
                            "create",
                            "read",
                            "delete",
                            "update",
                          ],
                          billing_permissions: [],
                          environments_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          functionalities_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          groups_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_causes_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_roles_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_types_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incidents_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          private_incidents_permissions: [],
                          invitations_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          playbooks_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          retrospective_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          roles_permissions: [],
                          services_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          severities_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          status_pages_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          workflows_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          team_id: 1,
                          name: "user",
                          slug: "user",
                          is_editable: true,
                          is_deletable: false,
                          incident_feedbacks_permissions: [
                            "read",
                            "create",
                            "update",
                          ],
                          form_fields_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          webhooks_permissions: ["read"],
                          audits_permissions: [],
                          secrets_permissions: ["create"],
                          id: "<role_id>",
                          deleted_at: null,
                          incident_permission_set_id:
                            "<role_incident_permission_set_id>",
                          pulses_permissions: ["create", "update", "read"],
                          alerts_permissions: ["create", "read"],
                          paging_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          sub_statuses_permissions: ["read"],
                          catalogs_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          communication_permissions: ["read"],
                          incident_communication_permissions: ["read"],
                          integrations_permissions: [],
                        },
                      },
                      on_call_role: {
                        data: {
                          id: "<on_call_role_id>",
                          team_id: 1,
                          name: "None",
                          slug: "no_access",
                          system_role: "no_access",
                          deleted_at: null,
                          created_at: "2024-04-30T11:35:05.372-07:00",
                          updated_at: "2024-04-30T11:35:05.372-07:00",
                          alerts_permissions: [],
                          api_keys_permissions: [],
                          audits_permissions: [],
                          escalation_policies_permissions: [],
                          groups_permissions: [],
                          integrations_permissions: [],
                          invitations_permissions: [],
                          on_call_roles_permissions: [],
                          schedules_permissions: [],
                          services_permissions: [],
                          shift_overrides_permissions: [],
                          workflows_permissions: [],
                          contacts_permissions: [],
                          live_call_routing_permissions: [],
                          heartbeats_permissions: [],
                          alert_urgency_permissions: [],
                          webhooks_permissions: [],
                          alert_sources_permissions: [],
                          schedule_override_permissions: [],
                          on_call_readiness_report_permissions: [],
                          alert_routing_rules_permissions: [],
                          alert_fields_permissions: [],
                          alert_groups_permissions: [],
                        },
                      },
                    },
                  },
                },
                severity: {
                  data: {
                    id: "<severity_id>",
                    type: "severities",
                    attributes: {
                      name: "SEV0",
                      slug: "sev0",
                      description:
                        "**Critical issue** that warrants public notification and liaison with executive teams, *e.g. whole site outage*",
                      severity: "critical",
                      color: "#E65252",
                      position: 1,
                      notify_emails: [],
                      slack_channels: [],
                      slack_aliases: [],
                      created_at: "2022-07-06T07:41:27.895-07:00",
                      updated_at: "2022-07-06T07:41:27.895-07:00",
                    },
                  },
                },
                in_triage_by: null,
                started_by: {
                  data: {
                    id: "<user_id>",
                    type: "users",
                    attributes: {
                      name: "Guest",
                      email: "guest@email.com",
                      phone: null,
                      phone_2: null,
                      first_name: "Guest",
                      last_name: "",
                      full_name: "Guest",
                      full_name_with_team: "[Rockit Rockets] Guest",
                      slack_id: "<slack_id>",
                      time_zone: "Europe/Stockholm",
                      updated_at: "2025-09-05T03:18:07.390-07:00",
                      created_at: "2025-09-04T11:26:59.737-07:00",
                    },
                    relationships: {
                      email_addresses: {
                        data: [
                          {
                            id: "<user_email_address_id>",
                            type: "user_email_addresses",
                          },
                        ],
                      },
                      phone_numbers: {
                        data: [],
                      },
                      devices: {
                        data: [],
                      },
                      role: {
                        data: {
                          created_at: "2022-07-06T07:41:27.733-07:00",
                          updated_at: "2024-10-08T23:57:01.838-07:00",
                          display_order: 3,
                          api_keys_permissions: [
                            "create",
                            "read",
                            "delete",
                            "update",
                          ],
                          billing_permissions: [],
                          environments_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          functionalities_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          groups_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_causes_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_roles_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incident_types_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          incidents_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          private_incidents_permissions: [],
                          invitations_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          playbooks_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          retrospective_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          roles_permissions: [],
                          services_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          severities_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          status_pages_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          workflows_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          team_id: 1,
                          name: "user",
                          slug: "user",
                          is_editable: true,
                          is_deletable: false,
                          incident_feedbacks_permissions: [
                            "read",
                            "create",
                            "update",
                          ],
                          form_fields_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          webhooks_permissions: ["read"],
                          audits_permissions: [],
                          secrets_permissions: ["create"],
                          id: "<role_id>",
                          deleted_at: null,
                          incident_permission_set_id:
                            "<role_incident_permission_set_id>",
                          pulses_permissions: ["create", "update", "read"],
                          alerts_permissions: ["create", "read"],
                          paging_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          sub_statuses_permissions: ["read"],
                          catalogs_permissions: [
                            "create",
                            "read",
                            "update",
                            "delete",
                          ],
                          communication_permissions: ["read"],
                          incident_communication_permissions: ["read"],
                          integrations_permissions: [],
                        },
                      },
                      on_call_role: {
                        data: {
                          id: "<on_call_role_id>",
                          team_id: 1,
                          name: "None",
                          slug: "no_access",
                          system_role: "no_access",
                          deleted_at: null,
                          created_at: "2024-04-30T11:35:05.372-07:00",
                          updated_at: "2024-04-30T11:35:05.372-07:00",
                          alerts_permissions: [],
                          api_keys_permissions: [],
                          audits_permissions: [],
                          escalation_policies_permissions: [],
                          groups_permissions: [],
                          integrations_permissions: [],
                          invitations_permissions: [],
                          on_call_roles_permissions: [],
                          schedules_permissions: [],
                          services_permissions: [],
                          shift_overrides_permissions: [],
                          workflows_permissions: [],
                          contacts_permissions: [],
                          live_call_routing_permissions: [],
                          heartbeats_permissions: [],
                          alert_urgency_permissions: [],
                          webhooks_permissions: [],
                          alert_sources_permissions: [],
                          schedule_override_permissions: [],
                          on_call_readiness_report_permissions: [],
                          alert_routing_rules_permissions: [],
                          alert_fields_permissions: [],
                          alert_groups_permissions: [],
                        },
                      },
                    },
                  },
                },
                mitigated_by: null,
                resolved_by: null,
                closed_by: null,
                cancelled_by: null,
                mitigation_message: null,
                resolution_message: null,
                cancellation_message: null,
                public_title: null,
                duplicate_incident_id: null,
                retrospective_progress_status: "not_started",
                zoom_meeting_id: null,
                zoom_meeting_start_url: null,
                zoom_meeting_join_url: null,
                zoom_meeting_password: null,
                zoom_meeting_pstn_password: null,
                zoom_meeting_h323_password: null,
                zoom_meeting_global_dial_in_numbers: [],
                shortcut_story_id: null,
                shortcut_story_url: null,
                shortcut_task_id: null,
                shortcut_task_url: null,
                asana_task_id: null,
                asana_task_url: null,
                github_issue_id: null,
                github_issue_url: null,
                gitlab_issue_id: null,
                gitlab_issue_url: null,
                jira_issue_key: null,
                jira_issue_id: null,
                jira_issue_url: null,
                google_meeting_id: null,
                google_meeting_url: null,
                trello_card_id: null,
                trello_card_url: null,
                linear_issue_id: null,
                linear_issue_url: null,
                zendesk_ticket_id: null,
                zendesk_ticket_url: null,
                motion_task_id: null,
                motion_task_url: null,
                clickup_task_id: null,
                clickup_task_url: null,
                slack_channel_name:
                  "incident-20250905-backstage-plugin-test-incident",
                slack_channel_id: "<incident_slack_channel_id>",
                slack_channel_url:
                  "https://slack.com/app_redirect?channel=<incident_slack_channel_id>&team=<team_id>",
                slack_channel_short_url: "https://root.ly/t232l1",
                slack_channel_deep_link:
                  "slack://channel?id=<incident_slack_channel_id>&team=<team_id>",
                slack_channel_archived: false,
                slack_last_message_ts: null,
                service_now_incident_id: null,
                service_now_incident_key: null,
                service_now_incident_url: null,
                opsgenie_incident_id: null,
                opsgenie_incident_url: null,
                opsgenie_alert_id: null,
                opsgenie_alert_url: null,
                victor_ops_incident_id: null,
                victor_ops_incident_url: null,
                pagerduty_incident_id: null,
                pagerduty_incident_number: null,
                pagerduty_incident_url: null,
                mattermost_channel_id: null,
                mattermost_channel_name: null,
                mattermost_channel_url: null,
                confluence_page_id: null,
                confluence_page_url: null,
                quip_page_id: null,
                quip_page_url: null,
                airtable_base_key: null,
                airtable_table_name: null,
                airtable_record_id: null,
                airtable_record_url: null,
                google_drive_id: null,
                google_drive_parent_id: null,
                google_drive_url: null,
                sharepoint_page_id: null,
                sharepoint_page_url: null,
                datadog_notebook_id: null,
                datadog_notebook_url: null,
                freshservice_ticket_id: null,
                freshservice_ticket_url: null,
                freshservice_task_id: null,
                freshservice_task_url: null,
                scheduled_for: null,
                scheduled_until: null,
                in_triage_at: null,
                started_at: "2025-09-05T02:33:44.675-07:00",
                detected_at: null,
                acknowledged_at: null,
                mitigated_at: null,
                resolved_at: null,
                closed_at: null,
                cancelled_at: null,
                created_at: "2025-09-05T02:33:44.799-07:00",
                updated_at: "2025-09-05T02:33:48.190-07:00",
                labels: {},
              },
              relationships: {
                causes: {
                  data: [],
                },
                subscribers: {
                  data: [
                    {
                      id: "<incident_subscriber_id>",
                      type: "incident_subscribers",
                    },
                  ],
                },
                roles: {
                  data: [
                    {
                      id: "<incident_role_assignment_id1>",
                      type: "incident_role_assignments",
                    },
                    {
                      id: "<incident_role_assignment_id2>",
                      type: "incident_role_assignments",
                    },
                  ],
                },
                environments: {
                  data: [
                    {
                      id: "<environment_id>",
                      type: "environments",
                    },
                  ],
                },
                incident_types: {
                  data: [
                    {
                      id: "<incident_type_id>",
                      type: "incident_types",
                    },
                  ],
                },
                services: {
                  data: [
                    {
                      id: "<service_id>",
                      type: "services",
                    },
                  ],
                },
                functionalities: {
                  data: [],
                },
                groups: {
                  data: [
                    {
                      id: "<group_id>",
                      type: "groups",
                    },
                  ],
                },
                events: {
                  data: [
                    {
                      id: "<incident_event_id1>",
                      type: "incident_events",
                    },
                    {
                      id: "<incident_event_id2>",
                      type: "incident_events",
                    },
                    {
                      id: "<incident_event_id3>",
                      type: "incident_events",
                    },
                    {
                      id: "<incident_event_id4>",
                      type: "incident_events",
                    },
                    {
                      id: "<incident_event_id5>",
                      type: "incident_events",
                    },
                  ],
                },
                action_items: {
                  data: [
                    {
                      id: "<incident_action_item_id1>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id2>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id3>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id4>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id5>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id6>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id7>",
                      type: "incident_action_items",
                    },
                    {
                      id: "<incident_action_item_id8>",
                      type: "incident_action_items",
                    },
                  ],
                },
                custom_field_selections: {
                  data: [],
                },
                feedbacks: {
                  data: [],
                },
                attachments: {
                  data: [],
                },
                slack_messages: {
                  data: [],
                },
              },
            },
          ],
          included: [
            {
              id: "<environment_id>",
              type: "environments",
              attributes: {
                slug: "development",
                name: "development",
                description: "Development Environment",
                color: "#047BF8",
                position: 1,
                notify_emails: [],
                slack_channels: [],
                slack_aliases: [],
                created_at: "2022-07-06T07:41:27.837-07:00",
                updated_at: "2022-07-06T07:41:27.837-07:00",
              },
            },
            {
              id: "<incident_type_id>",
              type: "incident_types",
              attributes: {
                slug: "default",
                name: "Default",
                description: "Used unless specific incident type is identified",
                color: "#047BF8",
                position: 1,
                notify_emails: [],
                slack_channels: [],
                slack_aliases: [],
                created_at: "2022-07-06T07:41:28.629-07:00",
                updated_at: "2022-07-06T07:41:28.629-07:00",
              },
            },
            {
              id: "<service_id>",
              type: "services",
              attributes: {
                name: "backstage-plugin-test-service",
                slug: "backstage-plugin-test-service",
                description: "Backstage Plugin Test Service",
                public_description: "",
                notify_emails: [],
                color: "#FAEBB7",
                status: "operational",
                position: 9,
                show_uptime: true,
                show_uptime_last_days: 60,
                slack_channels: [],
                slack_aliases: [],
                github_repository_name: null,
                github_repository_branch: "master",
                gitlab_repository_name: null,
                gitlab_repository_branch: "master",
                opsgenie_id: null,
                pagerduty_id: null,
                backstage_id: "component:default/backstage-plugin-test-service",
                external_id: null,
                cortex_id: null,
                service_now_ci_sys_id: null,
                environment_ids: ["<environment_id>"],
                service_ids: [],
                owner_group_ids: ["<group_id>"],
                owners_group_ids: ["<group_id>"],
                owner_user_ids: [],
                owners_user_ids: [],
                incidents_count: 1,
                alert_urgency_id: null,
                alerts_email_enabled: false,
                alerts_email_address: "service-<service_id>@email.rootly.com",
                alert_broadcast_enabled: false,
                alert_broadcast_channel: {},
                incident_broadcast_enabled: false,
                incident_broadcast_channel: {},
                created_at: "2025-09-05T02:19:33.876-07:00",
                updated_at: "2025-09-05T02:29:40.608-07:00",
              },
            },
            {
              id: "<group_id>",
              type: "groups",
              attributes: {
                slug: "backstage-plugin-test-team",
                name: "Backstage Plugin Test Team",
                description: "",
                color: "#F4CFD1",
                position: 5,
                notify_emails: [],
                slack_channels: [],
                slack_aliases: [],
                pagerduty_id: null,
                pagerduty_service_id: null,
                backstage_id: null,
                external_id: null,
                opsgenie_id: null,
                victor_ops_id: null,
                pagertree_id: null,
                cortex_id: null,
                service_now_ci_sys_id: null,
                user_ids: ["<user_id>"],
                admin_ids: [],
                incidents_count: 1,
                alert_urgency_id: null,
                alerts_email_enabled: false,
                alerts_email_address:
                  "group-<alert_email_address_id>@email.rootly.com",
                alert_broadcast_enabled: false,
                alert_broadcast_channel: {},
                incident_broadcast_enabled: false,
                incident_broadcast_channel: {},
                created_at: "2025-09-05T01:58:33.253-07:00",
                updated_at: "2025-09-05T01:58:48.834-07:00",
              },
              relationships: {
                users: {
                  data: [
                    {
                      id: "<user_id>",
                      type: "users",
                    },
                  ],
                },
              },
            },
          ],
          links: {
            self: "https://api.rootly.com/v1/incidents?include=environments%2Cservices%2Cfunctionalities%2Cgroups%2Cincident_types&page%5Bnumber%5D=1&page%5Bsize%5D=1",
            first:
              "https://api.rootly.com/v1/incidents?include=environments%2Cservices%2Cfunctionalities%2Cgroups%2Cincident_types&page%5Bnumber%5D=1&page%5Bsize%5D=1",
            prev: null,
            next: null,
            last: "https://api.rootly.com/v1/incidents?include=environments%2Cservices%2Cfunctionalities%2Cgroups%2Cincident_types&page%5Bnumber%5D=1&page%5Bsize%5D=1",
          },
          meta: {
            current_page: 1,
            next_page: null,
            prev_page: null,
            total_count: 1,
            total_pages: 1,
          },
        };
      },
    };
  },
};
